p8105_hw2_md4036
================
Margaret
2022-10-07

## Problem 0

This solution focuses on a reproducible report containing code and text
necessary for Problems 1-3, and is organized as an R Project. This was
not prepared as a GitHub repo; examples for repository structure and git
commits should be familiar from other elements of the course.

Throughout, we use appropriate text to describe our code and results,
and use clear styling to ensure code is readable.

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readxl)
library (dplyr)
```

### Problem 1

Below we import and clean data from
`NYC_Transit_Subway_Entrance_And_Exit_Data.csv`. The process begins with
data import, updates variable names, and selects the columns that will
be used in later parts fo this problem. We update `entry` from `yes` /
`no` to a logical variable. As part of data import, we specify that
`Route` columns 8-11 should be character for consistency with 1-7.

``` r
trans_ent = 
  read_csv(
    "./hw2data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

As it stands, these data are not “tidy”: route number should be a
variable, as should route. That is, to obtain a tidy dataset we would
need to convert `route` variables from wide to long format. This will be
useful when focusing on specific routes, but may not be necessary when
considering questions that focus on station-level variables.

The following code chunk selects station name and line, and then uses
`distinct()` to obtain all unique combinations. As a result, the number
of rows in this dataset is the number of unique stations.

``` r
trans_ent %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

The next code chunk is similar, but filters according to ADA compliance
as an initial step. This produces a dataframe in which the number of
rows is the number of ADA compliant stations.

``` r
trans_ent %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

To compute the proportion of station entrances / exits without vending
allow entrance, we first exclude station entrances that do not allow
vending. Then, we focus on the `entry` variable – this logical, so
taking the mean will produce the desired proportion (recall that R will
coerce logical to numeric in cases like this).

``` r
trans_ent %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

Lastly, we write a code chunk to identify stations that serve the A
train, and to assess how many of these are ADA compliant. As a first
step, we tidy the data as alluded to previously; that is, we convert
`route` from wide to long format. After this step, we can use tools from
previous parts of the question (filtering to focus on the A train, and
on ADA compliance; selecting and using `distinct` to obtain dataframes
with the required stations in rows).

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

### Problem 2

Below we import the `Trash-Wheel-Collection-Totals-7-2020-2.xlsx`. The
process begins with data import.

``` r
library(dplyr)
```

``` r
Mr_Trash_data =
  read_excel ("./hw2data/Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N550") %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(sports_balls = as.integer(round(sports_balls))) %>%
  mutate(new = 1, .before = dumpster)%>%
  mutate(year=as.numeric(year))

Mr_Trash_data
```

    ## # A tibble: 547 × 15
    ##      new dumps…¹ month  year date                weigh…² volum…³ plast…⁴ polys…⁵
    ##    <dbl>   <dbl> <chr> <dbl> <dttm>                <dbl>   <dbl>   <dbl>   <dbl>
    ##  1     1       1 May    2014 2014-05-16 00:00:00    4.31      18    1450    1820
    ##  2     1       2 May    2014 2014-05-16 00:00:00    2.74      13    1120    1030
    ##  3     1       3 May    2014 2014-05-16 00:00:00    3.45      15    2450    3100
    ##  4     1       4 May    2014 2014-05-17 00:00:00    3.1       15    2380    2730
    ##  5     1       5 May    2014 2014-05-17 00:00:00    4.06      18     980     870
    ##  6     1       6 May    2014 2014-05-20 00:00:00    2.71      13    1430    2140
    ##  7     1       7 May    2014 2014-05-21 00:00:00    1.91       8     910    1090
    ##  8     1       8 May    2014 2014-05-28 00:00:00    3.7       16    3580    4310
    ##  9     1       9 June   2014 2014-06-05 00:00:00    2.52      14    2400    2790
    ## 10     1      10 June   2014 2014-06-11 00:00:00    3.76      18    1340    1730
    ## # … with 537 more rows, 6 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, and abbreviated variable names
    ## #   ¹​dumpster, ²​weight_tons, ³​volume_cubic_yards, ⁴​plastic_bottles,
    ## #   ⁵​polystyrene

``` r
Professor_Trash_Data = 
  read_excel ("./hw2data/Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = "A2:M97") %>%
  janitor::clean_names()%>%
  drop_na (dumpster)%>%
  mutate (new = 1, .before = dumpster) 

view(Professor_Trash_Data)
```

\##now we combine Mr.Trash Wheel Data and Professor Trash Wheel Data

``` r
trash_wheel_combined = 
  bind_rows (Mr_Trash_data, Professor_Trash_Data)

view (trash_wheel_combined)
print(trash_wheel_combined)
```

    ## # A tibble: 641 × 15
    ##      new dumps…¹ month  year date                weigh…² volum…³ plast…⁴ polys…⁵
    ##    <dbl>   <dbl> <chr> <dbl> <dttm>                <dbl>   <dbl>   <dbl>   <dbl>
    ##  1     1       1 May    2014 2014-05-16 00:00:00    4.31      18    1450    1820
    ##  2     1       2 May    2014 2014-05-16 00:00:00    2.74      13    1120    1030
    ##  3     1       3 May    2014 2014-05-16 00:00:00    3.45      15    2450    3100
    ##  4     1       4 May    2014 2014-05-17 00:00:00    3.1       15    2380    2730
    ##  5     1       5 May    2014 2014-05-17 00:00:00    4.06      18     980     870
    ##  6     1       6 May    2014 2014-05-20 00:00:00    2.71      13    1430    2140
    ##  7     1       7 May    2014 2014-05-21 00:00:00    1.91       8     910    1090
    ##  8     1       8 May    2014 2014-05-28 00:00:00    3.7       16    3580    4310
    ##  9     1       9 June   2014 2014-06-05 00:00:00    2.52      14    2400    2790
    ## 10     1      10 June   2014 2014-06-11 00:00:00    3.76      18    1340    1730
    ## # … with 631 more rows, 6 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, and abbreviated variable names
    ## #   ¹​dumpster, ²​weight_tons, ³​volume_cubic_yards, ⁴​plastic_bottles,
    ## #   ⁵​polystyrene

### Data Description

This combined data set contains 641 rows and 15 columns. The total
weight of the trash collected by Professor Trash Wheel is 190.12 tons.
The total number of sports balls collected by Mr.Trash Wheel in 2020 is
6877 sports balls. In order to merge `Mr_Trash_data` and
`Professor_Trash_Data` a “new” column was added. The combined dataset
includes variables new, dumpster, month, year, date, weight_tons,
volume_cubic_yards, plastic_bottles, polystrene, cigarette_butts,
glass_bottles, grocery_bags, chip_bags, sports_balls and home_powered.

### Problem 3

Below we import the `pols-month.csv`, `unemployment.csv`, and `snp.csv`.
The process begins with data import.

``` r
polls_month_data =
  read_csv("./hw2data/pols-month.csv")  %>%
  janitor::clean_names()%>%
  separate(col= "mon", into = c("year","month","day"),sep = "-")%>%
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    day = as.integer(day)) %>%
  mutate(month = recode (month, "1"= "January", "2"="February", "3" = "March", "4"="April", "5"= "May", "6"= "June", "7"="July", "8"="August", "9"="September","10"= "October", "11"="November", "12"="December"), 
  president = recode (prez_gop, `0` ="dem", `1` ="gop", `2` ="gop"))%>%
  select(-prez_dem, -prez_gop, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
print(polls_month_data)
```

    ## # A tibble: 822 × 9
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 January        23      51     253      23      45     198 dem      
    ##  2  1947 February       23      51     253      23      45     198 dem      
    ##  3  1947 March          23      51     253      23      45     198 dem      
    ##  4  1947 April          23      51     253      23      45     198 dem      
    ##  5  1947 May            23      51     253      23      45     198 dem      
    ##  6  1947 June           23      51     253      23      45     198 dem      
    ##  7  1947 July           23      51     253      23      45     198 dem      
    ##  8  1947 August         23      51     253      23      45     198 dem      
    ##  9  1947 September      23      51     253      23      45     198 dem      
    ## 10  1947 October        23      51     253      23      45     198 dem      
    ## # … with 812 more rows

``` r
unemployment_data = 
  read.csv("./hw2data/unemployment.csv")%>%
  janitor::clean_names()%>%
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment_percent")%>%
  mutate(month = recode (month, "jan"= "January", "feb"="February", "mar" = "March", "apr"="April", "may"= "May", "jun"= "June", "jul"="July", "aug"="August", "sep"="September","oct"= "October", "nov"="November", "dec"="December"))

print(unemployment_data)
```

    ## # A tibble: 816 × 3
    ##     year month     unemployment_percent
    ##    <int> <chr>                    <dbl>
    ##  1  1948 January                    3.4
    ##  2  1948 February                   3.8
    ##  3  1948 March                      4  
    ##  4  1948 April                      3.9
    ##  5  1948 May                        3.5
    ##  6  1948 June                       3.6
    ##  7  1948 July                       3.6
    ##  8  1948 August                     3.9
    ##  9  1948 September                  3.8
    ## 10  1948 October                    3.7
    ## # … with 806 more rows

``` r
snp_data =
  read.csv("./hw2data/snp.csv") %>%
  janitor::clean_names() %>%
  separate(col = "date", into = c("month","day","year"), sep = "/") %>%
  select(-day)%>%
  select(year, month, everything())%>%
  mutate(year = as.integer(year),
  month = recode(month, `1`= "January", `2`="February", `3` = "March", `4`="April", `5`= "May", `6`= "June", `7`="July", `8`="August", `9`="September",`10`= "October", `11`="November", `12`="December"))

print(head(snp_data))
```

    ##   year    month   close
    ## 1   15     July 2079.65
    ## 2   15     June 2063.11
    ## 3   15      May 2107.39
    ## 4   15    April 2085.51
    ## 5   15    March 2067.89
    ## 6   15 February 2104.50

## Now we join the datasets together

``` r
combine_polls_snp =
  left_join(polls_month_data, snp_data)
```

    ## Joining, by = c("year", "month")

``` r
print(combine_polls_snp)
```

    ## # A tibble: 822 × 10
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem presi…¹ close
    ##    <int> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>   <dbl>
    ##  1  1947 January        23      51     253      23      45     198 dem        NA
    ##  2  1947 February       23      51     253      23      45     198 dem        NA
    ##  3  1947 March          23      51     253      23      45     198 dem        NA
    ##  4  1947 April          23      51     253      23      45     198 dem        NA
    ##  5  1947 May            23      51     253      23      45     198 dem        NA
    ##  6  1947 June           23      51     253      23      45     198 dem        NA
    ##  7  1947 July           23      51     253      23      45     198 dem        NA
    ##  8  1947 August         23      51     253      23      45     198 dem        NA
    ##  9  1947 September      23      51     253      23      45     198 dem        NA
    ## 10  1947 October        23      51     253      23      45     198 dem        NA
    ## # … with 812 more rows, and abbreviated variable name ¹​president

``` r
final3_combine =
  left_join(combine_polls_snp, unemployment_data)
```

    ## Joining, by = c("year", "month")

``` r
print(final3_combine)
```

    ## # A tibble: 822 × 11
    ##     year month     gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem presi…¹ close
    ##    <int> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>   <dbl>
    ##  1  1947 January        23      51     253      23      45     198 dem        NA
    ##  2  1947 February       23      51     253      23      45     198 dem        NA
    ##  3  1947 March          23      51     253      23      45     198 dem        NA
    ##  4  1947 April          23      51     253      23      45     198 dem        NA
    ##  5  1947 May            23      51     253      23      45     198 dem        NA
    ##  6  1947 June           23      51     253      23      45     198 dem        NA
    ##  7  1947 July           23      51     253      23      45     198 dem        NA
    ##  8  1947 August         23      51     253      23      45     198 dem        NA
    ##  9  1947 September      23      51     253      23      45     198 dem        NA
    ## 10  1947 October        23      51     253      23      45     198 dem        NA
    ## # … with 812 more rows, 1 more variable: unemployment_percent <dbl>, and
    ## #   abbreviated variable name ¹​president

\###Data Description The `polls_month_data`contained 822 rows and 9
columns. The variables include year,month, gov_gop, sen_gop, rep_gop,
gov_dem, sen_dem, rep_dem, and president. The “president” column is made
through combining the “prez_gop” and “prez_dem”. The years of this
dataset range from 1947 to 2015.

The `snp_data` contained 787 rows and 3 columns. The variables in
include year and month of the observation of the S&P index and closing
values of the S&P stock index on the associated year and month. The
variable “day” was removed. The years of this dataset range from 0 to
99. Additionally, the “year” was recoded from numbers to characters.

The `unemployment_data` contained 816 rows and 3 columns. The variables
include year, month,and unemployment percents. The years of this dataset
range from 1948 to 2015.

These three datasets were then combined and created a dataset with 822
rows and 11 columns. The variables combined to include a data set with
year, month, gov_gop, sen_gop, rep_gop,gov_dem, sen_dem, rep_dem,
president, close, and unemployment percents. The “close” variable is`NA`
because when it was merged, none of the data matched up. Additionally
the “unemployment_percent” variable only had a few match up while the
rest were indicated as `NA`. The years of this dataset range from 1947
to 2015.
